# Generated by Django 3.1.5 on 2021-01-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c2lUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='User Name')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=12, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=400, null=True, verbose_name='Address')),
            ],
        ),
    ]
